import time
from selenium import webdriver
from selenium.webdriver import ActionChains,Keys

drivers=webdriver.Chrome()
drivers.implicitly_wait(10)
# drivers.get(r'https://demoapps.qspiders.com/ui/keyboard?sublist=0')
drivers.get(r'https://testautomationpractice.blogspot.com/')
drivers.maximize_window()
time.sleep(2)
object=ActionChains(drivers)
'''demoapps'''
# keyb=drivers.find_element('xpath','//*[@id="demoUI"]/main/section/article/aside/div/aside/div/div/div/div/div/input')
# keyb.send_keys('selenium')
# object.key_down(Keys.CONTROL).send_keys('a').key_up(Keys.CONTROL).perform()
# time.sleep(2)
# object.key_down(Keys.CONTROL).send_keys('c').key_up(Keys.CONTROL).perform()
# time.sleep(1)
# object.key_down(Keys.BACKSPACE).perform()
# time.sleep(2)
# object.key_down(Keys.CONTROL).send_keys('v').key_up(Keys.CONTROL).perform()
# time.sleep(2)
'''testautomation'''
# keyb2=drivers.find_element('xpath','//*[@id="name"]')
# keyb2.send_keys('selenium')
# object.key_down(Keys.CONTROL).send_keys('a').key_up(Keys.CONTROL).perform()
# time.sleep(1)
# object.key_down(Keys.CONTROL).send_keys('c').key_up(Keys.CONTROL).perform()
# time.sleep(1)
# object.key_down(Keys.TAB).perform()
# object.key_down(Keys.CONTROL).send_keys('v').key_up(Keys.CONTROL).perform()
# time.sleep(2)
# keyb2.click()
# object.key_down(Keys.CONTROL).send_keys('a').key_up(Keys.CONTROL).perform()
# object.key_down(Keys.DELETE).perform()
# time.sleep(2)
# keyb2.send_keys('automation')
# keyb2.click()
# object.key_down(Keys.ARROW_RIGHT).send_keys(' test').key_up(Keys.ARROW_RIGHT).perform()
# time.sleep(4)
for i in range(1,7):
    object.key_down(Keys.PAGE_DOWN).perform()
    time.sleep(1)
drivers.find_element('xpath','//*[@id="input3"]').send_keys('SELENIUM')
time.sleep(1)
object.key_down(Keys.CONTROL).send_keys('a').key_up(Keys.CONTROL).perform()
object.key_down(Keys.DELETE).perform()
time.sleep(3)

