import time
from selenium import webdriver
drivers=webdriver.Chrome()
drivers.get(r'https://testautomationpractice.blogspot.com/')
drivers.maximize_window()
time.sleep(2)
drivers.get(r'https://demoapps.qspiders.com/')
time.sleep(2)
drivers.get(r'https://www.amazon.com/')
time.sleep(2)
drivers.back()
time.sleep(2)
drivers.back()
time.sleep(2)
drivers.forward()
time.sleep(2)
drivers.forward()
time.sleep(2)
drivers.refresh()
time.sleep(2)
